# https://www.elastic.co/guide/en/elasticsearch/reference/current/defining-roles.html#roles-management-file
# https://www.elastic.co/guide/en/elasticsearch/reference/current/security-privileges.html
# https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-users-and-roles.html
kind: Secret
apiVersion: v1
metadata:
  name: es-roles
stringData:
  roles.yml: |-
    demo:
      cluster: []
      indices:
        - names: 
            - "demo"
          privileges:
            - "all"
          allow_restricted_indices: false
---
apiVersion: v1
kind: Secret
metadata:
  name: es-developer
type: kubernetes.io/basic-auth
stringData:
  username: developer    # required field for kubernetes.io/basic-auth
  password: $DEVELOPER_PASSWORD # required field for kubernetes.io/basic-auth
  roles: demo  # optional, not part of kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: es-elastic
type: kubernetes.io/basic-auth
stringData:
  username: elastic    # required field for kubernetes.io/basic-auth
  password: $ELASTIC_PASSWORD # required field for kubernetes.io/basic-auth
  roles: superuser,kibana_admin,monitoring_user  # optional, not part of kubernetes.io/basic-auth