apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 8.3.2
  count: 1
  elasticsearchRef:
    name: demo
  http:
    service:
      spec:
        type: ClusterIP
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            limits:
              memory: 2Gi
              cpu: 2
            requests:
              memory: 700Mi
              cpu: 500m
  config:
    xpack:
      monitoring:
        kibana:
          collection:
            enabled: false
        collection:
          enabled: true
        ui:
          ccs:
            enabled: false
      discoverEnhanced:
        actions:
          exploreDataInChart:
            enabled: true